### ISSUE TITLE
Consider replacing plist crate with plist-rs

### ISSUE THREAD

**Issue by conradev** [kennytm/libimobiledevice-rust#1]
Heya! I built a pure Rust property list parser that might be worth using in this project: https://github.com/conradev/plist-rs

All you would need to add is bridging to `libplist-sys`

**Comment by kennytm** [comment]
@conradev It is already supported. https://github.com/kennytm/libimobiledevice-rust/blob/master/libplist/Cargo.toml#L25

**Comment by conradev** [comment]
Oh wow, I didn't even realize. Awesome! ð
